# Generated by Django 4.0.1 on 2022-01-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='num_active',
            field=models.IntegerField(default=0),
        ),
    ]
